version: "3"

services:
  strapi:
    image: pitersizovdev/strapitest:latest
    container_name: strapi-test
    build: .
    ports:
      - "544:1337"
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=C3254IyAQ9UnBdBuq91YrQ==,WEpaSO+T6nddGFNAkvr0NQ==,8gpnP7/LnYmM94hVbi4zGw==,Y4J6k9HQ/nPAxHViliwlCQ==
      - API_TOKEN_SALT=hVWjY7sigyhaIrB80j/YqA==
      - ADMIN_JWT_SECRET=hQ8A7O5RMMHAi1oMEn8IlA==
      - TRANSFER_TOKEN_SALT=cI/XcjYJCq7QtCSnMyZsuQ==
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/data/data.db
    volumes:
      - strapi-app-data:/usr/src/app/src
      - strapi-db-data:/data
    restart: always

volumes:
  strapi-app-data:
  strapi-db-data: